---
title: Emoji's in tekst gebruiken
hero_image: images/banner.png
description: Je kan Emoji's in tekst strings gebruiken in Scratch.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Emoji's in tekst gebruiken
