title: Defnyddio Emojis mewn testun
hero_image: images/banner.png
description: Teipio Emojis mewn llinynnau testun yn Scratch.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Defnyddio Emojis mewn testun
