---
title: Use emojis no texto
hero_image: images/banner.png
description: Adicione emojis em sequências de texto no Scratch.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Use emojis no texto
