---
title: Používejte emotikony v textu
hero_image: images/banner.png
description: Napište Emojis do textových řetězců ve Scratch.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Používejte emotikony v textu
