title: Usa emojis en el texto
hero_image: images/banner.png
description: Escribe emojis en cadenas de texto en Scratch.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Usa emojis en el texto
