title: استخدام الايموجي في النص
hero_image: images/banner.png
description: اكتب Emojis في سلاسل نصية في Scratch.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Use Emojis in text
