---
title: Użyj emotikonów w tekście
hero_image: images/banner.png
description: Wpisz emotikony w wyrażeniach tekstowych w Scratchu.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Użyj emotikonów w tekście
