title: Use Emojis in text
hero_image: images/banner.png
description: Type Emojis in text strings in Scratch.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Use Emojis in text
