title: Utiliser les émojis dans le texte
hero_image: images/banner.png
description: Taper des émojis dans des chaînes de texte dans Scratch.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Utiliser les émojis dans le texte
