title: Utilizzare emoji nel testo
hero_image: images/banner.png
description: Digita emoji nelle stringhe di testo in Scratch.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Utilizzare emoji nel testo
